### ISSUE TITLE
If just object check neighbor.name

### ISSUE THREAD

**Issue by technicallyrice27** [technicallyrice27/cs419_text_adventure#3]
Check neighbor.name for movement as it has to conform to:

go west
west
go staircase
staircase

**Comment by csDaniel** [comment]
neighbor.name has been added successfully. All room files have been updated to feature this. However they currently exist as a template and we'll need to go back in and refactor any of the text to make sure it actually says, 

neighborName=staircase

**Comment by technicallyrice27** [comment]
Great, this has been implemented.
